name: 'Staging Deploy'

on:
  push:
    branches:
      - main

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Bump package.json version
        run: npm version minor

      - name: Commit changes
        run: |
          git config --local user.email "bianca.machado@external.clevercorporate.com"
          git config --local user.name "bcm-clever"
          git commit -a -m "Bump package.json version [skip ci]"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: qa3
